M48
; DRILL file {KiCad 8.0.7} date 2025-03-14T10:19:42+0100
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-03-14T10:19:42+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.7
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X62.0Y-63.2
X62.0Y-135.7
X202.0Y-63.2
X202.0Y-135.7
M30
